### PR TITLE
attempt to replicate

### PR DESCRIPTION
**Pull request by dblythy**

### CODE REVIEW

**Comment by dblythy** [comment]
Hi @stephannielsen, I have attempted to replicate but have been unsuccessful. I tried via the dashboard and via code.

My changes here are:

`npm start` automatically creates a real user with `id`, a relation with that user, and then runs the script `script.js`, which calls the cloud function with headers.

On my end, everything runs as expected.

**Comment by stephannielsen** [comment]
Awesome @dblythy, thank you. I will take a closer look.

What Node version are you using locally? I have only tested with v16/lts so far.

**Comment by dblythy** [comment]
I am using:

Node v16.10.0
NPM 7.24.0
macOS 12.4

**Comment by stephannielsen** [comment]
@dblythy 

I am not sure why your approach works right away. But I managed to take a few things from your automation and improve the main branch with it.

Could you check the main branch again. The as-is version should fail with Parse SDK JS >= 3.4.2. If you modify line 75 in `app.ts`, it should work again. With SDK <= 3.4.1, both approaches work.

`req["userFromJWT"] = parseUser; // Add .toPointer() to make this work with Parse SDK >= 3.4.2`

**Comment by stephannielsen** [comment]
I tried removing the `fetch` during authentication on your branch but that didn't produce the error to happen, it still works then.

**Pull request closed without merging**
